// AUTO-GENERATED by scripts/previews.mjs — do not edit by hand.
// Real screenshots of each demo, captured at 1440px and 390px and optimised to
// WebP. The portfolio renders these instead of embedding the live demos.

export type PreviewShot = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export type DemoPreview = { desktop: PreviewShot; mobile: PreviewShot };

export const previews: Record<string, DemoPreview> = {
  "interior": {
    "desktop": {
      "src": "/previews/interior-desktop.webp?v=2e26cc9c",
      "width": 1120,
      "height": 1836,
      "blurDataURL": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACQAwCdASoOABcAPxl2slEspySisAgBkCMJZQC7AAmyorAS2rdgAP6RbV8uSAt6jy4O3SjhnmcgCD3D/gRIcNWMLThiSfo/alhgre8eWiMWSDdQtxULlOxa22kza/CdoH9Iwt1mgjBy/Ji03MgAAA=="
    },
    "mobile": {
      "src": "/previews/interior-mobile.webp?v=f6513548",
      "width": 430,
      "height": 1720,
      "blurDataURL": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAABQBQCdASoOADgAPxmCuFYsqCUjqAgBkCMJYwDE3AgR8iUeepEOIVJBXi5O+wMlZK28nmgA/t7cpwCVErxzz07YJiMrRUa4P6yUZtIvbHRehvUBHelK7O55v8OpsjXGTOS5AurG+QeNo+/pAQWSk4UHmMmO8Kck5FJXLbOKSsYDo9VkLHrMP1H5nyTTrd6rkrD0KtvEIa6+pGN6zRbXbfSdWdQxc6qUcpscA+aQgjMFRGoj+TUYITKkeagAAA=="
    }
  },
  "salon": {
    "desktop": {
      "src": "/previews/salon-desktop.webp?v=6f794847",
      "width": 1120,
      "height": 1836,
      "blurDataURL": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAACwAwCdASoOABcAPxl2slEspySisAgBkCMJZQAASrZeR2YDIcoQAAD+5fC20AQmSbuteqfcnrXvA9B1zllQQRvaF7g69+YXXcuQpHuTjw3FGEqK6RwTOcKcuZr8/FYMIketqkWzSH0wnSzXU8HsAAAA"
    },
    "mobile": {
      "src": "/previews/salon-mobile.webp?v=1d52941c",
      "width": 430,
      "height": 1720,
      "blurDataURL": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAQBACdASoOADgAPwlyslCrpyUisAwBcCEJZwDKtCHfUUC+bF0ALMXNAAD+6+CJc4s6A/XzCnHW8MQ4YEf5o0vZUOp8mwfu4M4E4bRdTZ4RT/ZuYrp32QrEfyx/lwB7WcI1AVc7juVTUF6RXXXOD+lXeAAAAA=="
    }
  },
  "restaurant": {
    "desktop": {
      "src": "/previews/restaurant-desktop.webp?v=0f7f9320",
      "width": 1120,
      "height": 1836,
      "blurDataURL": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADQAwCdASoOABcAPxl4s1CspySisAgBkCMJZQC/OCPpsGy+zf0Gi5AA/uRHmOla/fnZpjkQNqXwWK+2JNqdfaU5Nt3REyfUR1F5YUqMz1cQ0dTdj1xHXD65ttRHSAfa9PxJsyOjnfb/Q7OyyWUXi7kE5Nw2NcjoAAA="
    },
    "mobile": {
      "src": "/previews/restaurant-mobile.webp?v=8f5fd6a0",
      "width": 430,
      "height": 1720,
      "blurDataURL": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABwBQCdASoOADgAPxl8tFKsp6UisBgIAZAjCUAWHYIqc9YWlvlpB7IJW+2B6Z+aPAAXQm2AAP7NnflmDmROwah5EW08edn0DzohjpHdidDRuIi8m+7BogWqNrjn3TXMIgeDu1jz29i6Spg1v/4AVOKcVHfyFAtx8cY4PK0nDBD0XELHet2K/pladbv7mPpwCRV6gOEOYAA="
    }
  },
  "clinic": {
    "desktop": {
      "src": "/previews/clinic-desktop.webp?v=1907e775",
      "width": 1120,
      "height": 1836,
      "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASoOABcAPxl2slEspySisAgBkCMJZwAAXBYG9jSC5I2M9qhQAP7G+GhAXpKN45FUlU8W0ZuZR63ttl0mTBp9IIOluFjhlWQ7bglmZN8jH4AAAA=="
    },
    "mobile": {
      "src": "/previews/clinic-mobile.webp?v=edaad80c",
      "width": 430,
      "height": 1720,
      "blurDataURL": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAADQBACdASoOADgAPvlmqFCqpaQit+gBUB8JQAARHcHX8Ae0wMfOMYakobtzm9VUAADLT560JbelVXb7CRIFg3svLfEJ74ksv5Mq67dyc3dZPPAjps9dMWESkyJ5Kpe3da8ZgjC41lNq80qOFf+poq+rdowsusaE95tWsvWDoj8nxyvOKxr821NhEBfLCbbUKtK0gRBA/hxv0+rk81oUsuXpTTe8XAAA"
    }
  },
  "school": {
    "desktop": {
      "src": "/previews/school-desktop.webp?v=e55d5d85",
      "width": 1120,
      "height": 1836,
      "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAwCdASoOABcAPxl2s1EspySisAgBkCMJQBfnA9CxHEzivs52nuAA/ZsZoHcdyEg+I0xc8BGgZ6jWoZLM453uUM1bhikti3TfgfRIvJQ8tXQGT6wIFTFZB+DsYo/TitQAAA=="
    },
    "mobile": {
      "src": "/previews/school-mobile.webp?v=19e29102",
      "width": 430,
      "height": 1720,
      "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACQBACdASoOADgAPw1ur1CsJiQisAwBgCGJYwC/7CHWviItN9yZefqSVCVGPCAA/lv7kzy0f5BMyF/BCesVwU1xHuB2lMABj6peVnK5OaOqfFFu+VC+9miAP1SLl+Hom87rBkRNg+/SV9aorCkc3wszFG27Y6B3W8vEb0YXyPWMZJt5RsROrrcCOgAAAA=="
    }
  },
  "realestate": {
    "desktop": {
      "src": "/previews/realestate-desktop.webp?v=fc90c77d",
      "width": 1120,
      "height": 1836,
      "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACQAwCdASoOABcAPxl0sVCspqSisAgBkCMJQAALFxtKMjM/KCiAAP7aUKlkcYtp+YgUw+PT4HFmBeJa2I7LTZIc2z39tbqOEd7/9smETRJgL1sV1JngQAAA"
    },
    "mobile": {
      "src": "/previews/realestate-mobile.webp?v=b5d5b75d",
      "width": 430,
      "height": 1720,
      "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwBACdASoOADgAPxF2q1CsJ6OisAwBgCIJYwDA46pw1v76n1TnzlH9hlDjFoQBGAAA/uKhem2GjQxQtVYfKOeKAnwSO/OiKUoX26xCkA5CafQrgPSi/gogFVTF0nIJFVFxx3cwSspi9JQxSha7gGp+iTqjQsL6z7tIMmZRNCPp3PhD7XFQS69LTCRvtokAAAA="
    }
  },
  "travel": {
    "desktop": {
      "src": "/previews/travel-desktop.webp?v=25927671",
      "width": 1120,
      "height": 1836,
      "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACwAwCdASoOABcAPxl4slEspySisAgBkCMJQBdgA3SbEgxghC3nAAD+3MzB70KNq8WloxTr+Ei6kArHkEQJWOAt5QY4PzAn3ChZmmr6A+8UujULuvXddM6H/qrWvwUaJgGYnpiWW1igYgwAAAA="
    },
    "mobile": {
      "src": "/previews/travel-mobile.webp?v=396e4d22",
      "width": 430,
      "height": 1720,
      "blurDataURL": "data:image/webp;base64,UklGRtIAAABXRUJQVlA4IMYAAACQBgCdASoOADgAPxl+slKsqKSisBgIAZAjCUAVhCDX27b/PAA00IXsNx0V6gvnN5Yww9w2Y5yQcucKakhQAP72z0xUF52b+vUya6uCQO3bH/cKV3bLDMN/cSejpVNr+P2M0CbSJ1i2ELSFraz7r3TU+CuZAKrA9VLkERWK5ScmbHOiwqeFnj1hEnGPAoDJR2Ldgt1kfFGgaIFYfn0VLDYjUPkKbqHZeHDx3iYGREjDUuX/aRpykfinok/AuoTVVb4R97IAAAA="
    }
  },
  "fitness": {
    "desktop": {
      "src": "/previews/fitness-desktop.webp?v=850b4fe0",
      "width": 1120,
      "height": 1836,
      "blurDataURL": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAwBACdASoOABcAPxl0slEspqSisAgBkCMJZQAAVPLszqB3xd9klJxiyfgA/qoRGt7+nz92Iu5TJYnUbu60FSFriW/M3UVE/wQf9jYsvBnHAUBLifDjYSsS17Y/NCvNQWwcX0CCcUcgQ9hkvEUJk1YQgAA="
    },
    "mobile": {
      "src": "/previews/fitness-mobile.webp?v=2a708d63",
      "width": 430,
      "height": 1720,
      "blurDataURL": "data:image/webp;base64,UklGRvQAAABXRUJQVlA4IOgAAADQBQCdASoOADgAPv1qqlCrJiQit+gBYB+JQAFgBFHj+2NdUvVEDjbjKS/PxEFRdB8xY9Tfz6b4AP7pVLaFDXBQeAkYXY+POGp1Wp4jd8k34bVmwkub1jjjJXaHPwxrXkYuay2Jkt0J9mHyfGhGrYHVB6uudWVTlwmtTnBNG0nbOvSy+rKlxmp7p0V8DmYDnfrw/8B0thmWJz9nHG4bETLH+3T+A1iGqQX8TRId5odhqPNX9IB/hdl5svRyxst3OfWw8TpPnCwpMPquXeRuJ0TKID1QRdyAVdnwz3TrGulJgG4tw2XTN1gA"
    }
  },
  "resort": {
    "desktop": {
      "src": "/previews/resort-desktop.webp?v=321d63cc",
      "width": 1120,
      "height": 1836,
      "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADQAwCdASoOABcAPxl2s1EspySisAgBkCMJQBdmUABv4mcYvCuaW0AA/qifK1XvsqDoVi2ZxE3wcZ6WeDgjL97jVAvc0xlU1+8Vrx6ioXAxY0Sfy7yadkS9cLmBRUZpwjVQCYgo38jR5B/wAAA="
    },
    "mobile": {
      "src": "/previews/resort-mobile.webp?v=dda78b06",
      "width": 430,
      "height": 1720,
      "blurDataURL": "data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAADQBQCdASoOADgAPxl+tlSsp6SjKAqpkCMJZACpJ2QFKr7B5Hb45KtYKebjADcsz3i9GZmZjbMAAP4itOdj8Fx/i6esQBebuy4xt1WkpFnZfGI8PrjTkOAIL1F0i8wggCtT436Ou8mlUPWdpxmU79PkEVHThrZOTFko1NYl3IWY6KXGnTrBGAOW8MdPd6vEtl/CZ/7AElLwwzov0DSj7AYLdmo8zuWZ9+eLIXl9FOEIiUpF8I2/dmgROifmtcdPMgK7ToRRtApoWiye40AAAA=="
    }
  },
  "boutique": {
    "desktop": {
      "src": "/previews/boutique-desktop.webp?v=4bfadfd0",
      "width": 1120,
      "height": 1836,
      "blurDataURL": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABQBACdASoOABcAPxl0slCspqSisAgBkCMJbACsACFT99dBjnvb4fLr364AAP7U7Kl90UbBZH0bUOmLbIn8+l63edvAPfx3eeU9S2Y6gUYs6L3hDPNYJWjTVDoe2/lfhNZ9cXEXn2xaBZjndbrqIgh0UMpk/YKxTrfpDHj+/gFlsRzV1Wc5IE7svz5VErMzZUnOz3AA"
    },
    "mobile": {
      "src": "/previews/boutique-mobile.webp?v=4b44d510",
      "width": 430,
      "height": 1720,
      "blurDataURL": "data:image/webp;base64,UklGRswAAABXRUJQVlA4IMAAAABQBQCdASoOADgAPw1wsVCsJqUisAwBgCGJagDNwCHYfKFqxWjnfwmD0Cmat2Db0HUaoAAA3meP2MQF4jGGB33Cbp94+vqWxzP3zcvr5c2QdVa8+38NrTxyoJQ873UDMOvYH9yE/fYxbpuqY5FgMnORmfWP9GzAmPg1sKuTJDeH5qpUzujfJdBbtPv4Qs66ipqAIKr2U2pNFluGDx77/i6kIxIkTcsDYxWS6Kdj4euU/vuGsYE8/KCDX5Na7QZ4AAA="
    }
  }
};

export function preview(slug: string): DemoPreview | undefined {
  return previews[slug];
}
