/**
 * Captures real desktop and mobile screenshots of every demo and writes
 * optimised WebP previews to public/previews, plus a blur-placeholder manifest.
 *
 * The portfolio must never embed the live demos — these assets are what the
 * showcase renders. Re-run after any demo design change.
 *
 * Usage: npm run previews          (needs `npm run start` on :3000)
 *        npm run previews salon    (one demo)
 */
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
import sharp from 'sharp';

const BASE = process.env.QA_BASE ?? 'http://localhost:3000';

const SLUGS = [
  'salon',
  'restaurant',
  'clinic',
  'school',
  'realestate',
  'travel',
  'fitness',
  'interior',
  'resort',
  'boutique',
];

const only = process.argv.slice(2);
const slugs = only.length ? only : SLUGS;

const OUT = fileURLToPath(new URL('../public/previews/', import.meta.url));
await mkdir(OUT, { recursive: true });

/** Tall captures so the preview frame can pan on hover. */
const SHOTS = [
  { key: 'desktop', width: 1440, height: 900, capture: 2360, out: 1120, quality: 72 },
  { key: 'mobile', width: 390, height: 844, capture: 1560, out: 430, quality: 74 },
];

const browser = await chromium.launch();

// Start from whatever is already recorded, so re-running one demo never drops
// the other nine from the manifest.
let manifest = {};
try {
  const existing = await import(new URL('../lib/previews.ts', import.meta.url).href).catch(() => null);
  if (existing?.previews) manifest = { ...existing.previews };
} catch {
  /* first run */
}
if (!Object.keys(manifest).length) {
  try {
    const src = await readFile(fileURLToPath(new URL('../lib/previews.ts', import.meta.url)), 'utf8');
    const json = src.slice(src.indexOf('= {', src.indexOf('export const previews')) + 2, src.lastIndexOf('};') + 1);
    manifest = JSON.parse(json);
  } catch {
    manifest = {};
  }
}

for (const slug of slugs) {
  manifest[slug] = {};

  for (const shot of SHOTS) {
    const ctx = await browser.newContext({
      viewport: { width: shot.width, height: shot.height },
      deviceScaleFactor: 2,
      isMobile: shot.key === 'mobile',
      hasTouch: shot.key === 'mobile',
      reducedMotion: 'reduce',
    });
    const page = await ctx.newPage();
    await page.goto(`${BASE}/${slug}`, { waitUntil: 'networkidle', timeout: 90_000 });

    await page.evaluate(async () => {
      // The PlaxWeb badge is meta — it must not appear inside a preview.
      document.querySelector('[data-plax-demo-chrome]')?.remove();
      document.querySelectorAll('[data-reveal]').forEach((n) => n.setAttribute('data-reveal', 'in'));
      const step = window.innerHeight * 0.7;
      for (let y = 0; y < Math.min(document.body.scrollHeight, 4000); y += step) {
        window.scrollTo(0, y);
        await new Promise((r) => setTimeout(r, 130));
      }
      window.scrollTo(0, 0);
    });
    await page.waitForTimeout(1400);

    // fullPage + a sharp extract is deterministic; `clip` alone is capped at
    // the viewport, which silently gives you a fold-height preview.
    const raw = await page.screenshot({ fullPage: true });
    const dpr = 2;
    const meta = await sharp(raw).metadata();
    const cropHeight = Math.min(shot.capture * dpr, meta.height);

    const file = `${slug}-${shot.key}.webp`;
    const pipeline = sharp(raw)
      .extract({ left: 0, top: 0, width: meta.width, height: cropHeight })
      .resize({ width: shot.out })
      .webp({ quality: shot.quality, effort: 6 });
    const info = await pipeline.toFile(`${OUT}${file}`);

    // The filename is stable, so Next's image optimiser (and every browser and
    // CDN in between) will happily keep serving a screenshot taken before the
    // demo was redesigned. Hashing the bytes into the URL makes a re-shot
    // preview a genuinely new resource.
    const version = createHash('sha1').update(await readFile(`${OUT}${file}`)).digest('hex').slice(0, 8);

    // 14px blur placeholder, inlined so cards never flash empty.
    const blur = await sharp(raw)
      .extract({ left: 0, top: 0, width: meta.width, height: cropHeight })
      .resize({ width: 14 })
      .webp({ quality: 28 })
      .toBuffer();

    manifest[slug][shot.key] = {
      src: `/previews/${file}?v=${version}`,
      width: info.width,
      height: info.height,
      blurDataURL: `data:image/webp;base64,${blur.toString('base64')}`,
    };

    console.log(`${file.padEnd(26)} ${info.width}×${info.height}  ${(info.size / 1024).toFixed(0)}kB`);
    await ctx.close();
  }
}

await browser.close();

const body = `// AUTO-GENERATED by scripts/previews.mjs — do not edit by hand.
// Real screenshots of each demo, captured at 1440px and 390px and optimised to
// WebP. The portfolio renders these instead of embedding the live demos.

export type PreviewShot = {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
};

export type DemoPreview = { desktop: PreviewShot; mobile: PreviewShot };

export const previews: Record<string, DemoPreview> = ${JSON.stringify(manifest, null, 2)};

export function preview(slug: string): DemoPreview | undefined {
  return previews[slug];
}
`;

await writeFile(fileURLToPath(new URL('../lib/previews.ts', import.meta.url)), body);
console.log('\nwrote lib/previews.ts');
